spring:
  application:
    name: batch

  batch:
    job:
      enabled: false
    # 자동으로 batch 스키마 생성 방징
    jdbc:
        initialize-schema: never

  config:
    import:
      - properties/payment/payment.client.yml
      - properties/payment/payment.rdb.yml
      - properties/payment/payment.batch.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8081