spring:
  application:
    name: batch

  batch:
    job:
      enabled: false

  config:
    import:
      - properties/payment/payment.toss.yml
      - properties/payment/payment.rdb.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8081

app:
  batch:
    enabled: true
    jobs:
      payment-recovery:
        enabled: true
        cron: "0 */5 * * * *"
