spring:
  flyway:
    enabled: false  # (중요) 기본 Flyway Auto-run 끄고, 우리가 만든 authFlyway만 실행

payment:
  flyway:
    locations: classpath:db/migration/v1/payment
    schema: payment
    history-table: flyway_schema_history_payment