org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

group=com.raio.ai
version=0.1.0

#core
grpc=:grpc
grpcServer=:grpc:grpc-server
grpcClient=:grpc:grpc-client

#user
user=:user
userApi=:user:user-api
userDomain=:user:user-api:user-domain
userException=:user:user-api:user-exception
userReadModel=:user:user-api:user-readmodel
userApplication=:user:user-application
userRdbAdapter=:user:user-rdb-adapter
userWebMvcAdapter=:user:user-webmvc
userBatchAdapter=:user:user-batch
userGrpcClientAdapter=:user:user-grpc-client-adapter

# stream
stream=:stream
streamApi=:stream:stream-api
streamDomain=:stream:stream-api:stream-domain
streamException=:stream:stream-api:stream-exception
streamReadModel=:stream:stream-api:stream-readmodel
streamApplication=:stream:stream-application
streamRdbAdapter=:stream:stream-rdb-adapter
streamWebMvcAdapter=:stream:stream-webmvc
streamBatchAdapter=:stream:stream-batch

# chat
chat=:chat
chatApi=:chat:chat-api
chatDomain=:chat:chat-api:chat-domain
chatException=:chat:chat-api:chat-exception
chatReadModel=:chat:chat-api:chat-readmodel
chatApplication=:chat:chat-application
chatRdbAdapter=:chat:chat-rdb-adapter
chatWebMvcAdapter=:chat:chat-webmvc
chatBatchAdapter=:chat:chat-batch
chatWebSocketAdapter=:chat:chat-websocket
chatSocketAdapter=:chat:chat-socket-adapter
chatModerationAdapter=:chat:chat-moderation-adapter
chatHuggingFaceAdapter=:chat:chat-huggingface-adapter

# donation
donation=:donation
donationApi=:donation:donation-api
donationDomain=:donation:donation-api:donation-domain
donationException=:donation:donation-api:donation-exception
donationReadModel=:donation:donation-api:donation-readmodel
donationApplication=:donation:donation-application
donationRdbAdapter=:donation:donation-rdb-adapter
streamRedisAdapter=:stream:stream-redis-adapter
donationWebMvcAdapter=:donation:donation-webmvc
donationBatchAdapter=:donation:donation-batch
donationSocketAdapter=:donation:donation-socket
donationGrpcClientAdapter=:donation:donation-grpc-client-adapter

# =========================
# payment-service
# =========================
paymentService=:payment-service
paymentServiceFlyway=:payment-service:payment-service-flyway

# payment
payment=:payment-service:payment
paymentApi=:payment-service:payment:payment-api
paymentDomain=:payment-service:payment:payment-api:payment-domain
paymentException=:payment-service:payment:payment-api:payment-exception
paymentReadModel=:payment-service:payment:payment-api:payment-readmodel
paymentApplication=:payment-service:payment:payment-application
paymentRdbAdapter=:payment-service:payment:payment-rdb-adapter
paymentWebMvcAdapter=:payment-service:payment:payment-webmvc
paymentClientAdapter=:payment-service:payment:payment-client-adapter
paymentBatchAdapter=:payment-service:payment:payment-batch
paymentGrpcClientAdapter=:payment-service:payment:payment-grpc-client-adapter

# wallet
wallet=:payment-service:wallet
walletApi=:payment-service:wallet:wallet-api
walletDomain=:payment-service:wallet:wallet-api:wallet-domain
walletException=:payment-service:wallet:wallet-api:wallet-exception
walletReadModel=:payment-service:wallet:wallet-api:wallet-readmodel
walletProto=:payment-service:wallet:wallet-api:wallet-proto
walletApplication=:payment-service:wallet:wallet-application
walletRdbAdapter=:payment-service:wallet:wallet-rdb-adapter
walletWebMvcAdapter=:payment-service:wallet:wallet-webmvc
walletClientAdapter=:payment-service:wallet:wallet-client-adapter
walletBatchAdapter=:payment-service:wallet:wallet-batch
walletGrpcServerAdapter=:payment-service:wallet:wallet-grpc-server-adapter

# settlement
settlement=:payment-service:settlement
settlementApi=:payment-service:settlement:settlement-api
settlementDomain=:payment-service:settlement:settlement-api:settlement-domain
settlementException=:payment-service:settlement:settlement-api:settlement-exception
settlementReadModel=:payment-service:settlement:settlement-api:settlement-readmodel
settlementApplication=:payment-service:settlement:settlement-application
settlementRdbAdapter=:payment-service:settlement:settlement-rdb-adapter
settlementWebMvcAdapter=:payment-service:settlement:settlement-webmvc
settlementClientAdapter=:payment-service:settlement:settlement-client-adapter
settlementBatchAdapter=:payment-service:settlement:settlement-batch
settlementGrpcClientAdapter=:payment-service:settlement:settlement-grpc-client-adapter