spring:
  flyway:
    enabled: false  # (중요) 기본 Flyway Auto-run 끄고, 우리가 만든 userFlyway만 실행

user:
  flyway:
    schema: user
    locations: classpath:db/migration/v1/user
    history-table: flyway_schema_history_user
