spring:
  config:
    import:
      - classpath:properties/payment/payment.client.yml
      - optional:classpath:properties/payment/payment.batch.yml
      - classpath:properties/payment-service/payment-service.rdb.yml
