spring:
  config:
    import:
      - classpath:properties/payment/payment.client.yml
      - classpath:properties/payment/payment.rdb.yml
      - optional:classpath:properties/payment/payment.batch.yml